#!/bin/sh /etc/rc.common

START=90

USE_PROCD=1

ZT_COMMAND=/usr/bin/zerotier-one
HOME_DIR=/var/lib/zerotier-one
NETWORK_DIR=$HOME_DIR/networks.d
DEVICEMAP=$HOME_DIR/devicemap
SECRET_FILE=$HOME_DIR/identity.secret
PID_FILE=$HOME_DIR/zerotier-one.pid

setup_devicemap() {
	local cfg="$1"
	local proto networkid

	config_get proto "$cfg" 'proto'
	config_get networkid "$cfg" 'networkid'

	[ $proto == "zerotier" ] && {
		echo "$networkid=zt-$cfg" >> $DEVICEMAP
	}
}

setup_global() {
	local cfg="$1"
	local secret
	config_get secret "$cfg" 'secret' generate

	mkdir -p $NETWORK_DIR
	 : > $DEVICEMAP

	if [ "$secret" = "generate" ]; then
		echo "Generate secret - please wait..."
		local tmp="/tmp/zt.$cfg.secret"
		zerotier-idtool generate "$tmp" > /dev/null
		secret="$(cat $tmp)"
		rm "$tmp"

		uci set zerotier.$cfg.secret="$secret"
		uci commit zerotier
	fi

	if [ -n "$secret" ]; then
		echo "$secret" > $SECRET_FILE
	fi
}

service_triggers() {
	procd_add_reload_trigger zerotier
}

start_service() {
	config_load 'zerotier'
	config_foreach setup_global 'global'
	config_load 'network'
	config_foreach setup_devicemap 'interface'

	procd_open_instance
	procd_set_param command $ZT_COMMAND -d $HOME_DIR
	procd_close_instance
}

stop_service() {
	[ -f $PID_FILE ] && {
		kill `cat $PID_FILE`
	}
}

